on: push

jobs:
  compile-windows:
    name: Compile Windows binary
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install rich
      - name: Build executable
        run: pyinstaller -w --onefile tree2.py 
  # release-bin:
  #   name: Release binaries
  #   runs-on: windows-latest
  #   steps:
  #     - name: Create Release
  #     - 
