on: push

jobs:
  compile-windows:
    name: Compile Windows binary
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install rich
      - name: Build executable
        run: pyinstaller -w --onefile tree2.py 
      - name: Get the latest tag
        id: tag
        run: |
          $TAG_NAME = Get-Date -Format "yyyyMMddHHmmss"
          echo "tag_name=$TAG_NAME" >> $env:GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.tag_name }}
          name: Release ${{ env.tag_name }}
          draft: false
          prerelease: false

      - name: Upload binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/tree2.exe
          asset_name: tree2.exe
          asset_content_type: application/octet-stream